Update test.yml (#8)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,1 +1,56 @@
+---
 
+name: "Manually dispatched matrix tests"
+on:
+  workflow_dispatch:
+
+jobs:
+  prepare_roles_list:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout current code
+        uses: actions/checkout@v3
+
+      - name: Get changed files in the roles folder
+        id: changed-roles-files
+        uses: tj-actions/changed-files@v35
+        with:
+          files: roles/**
+          json: true
+          dir_names: true
+          dir_names_max_depth: 2
+
+    outputs:
+      matrix: ${{ steps.changed-roles-files.outputs.all_changed_files }}
+
+  matrix_test:
+    runs-on: ubuntu-latest
+    needs: prepare_roles_list
+
+    strategy:
+      matrix:
+        role: ${{ fromJson(needs.prepare_roles_list.outputs.matrix) }}
+
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
+
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.9'
+
+      - name: Run linter for all roles in roles folder
+        run: |
+          echo -e "=== Install ansible-lint ===\n"
+          pip install ansible ansible-lint
+          echo -e "=== Run ansible-lint for all roles ===\n"
+          nofail=0
+          echo "=== Running linter in ${{ matrix.role }} ==="
+          pushd ${{ matrix.role }}
+          ansible-lint . && excode=$? || excode=$?
+          if [ "${excode}" != "0" ]; then
+            echo "=== !!! found errors for ${{ matrix.role }} !!! ==="
+            exit 1
+          fi
+          popd
